FROM mcr.microsoft.com/playwright:v1.52.0-noble

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .

CMD ["npx", "playwright", "test", "--config=e2e/playwright.config.ts"]
